### ISSUE TITLE
Make s-nomp sidechain compatible

### ISSUE THREAD

**Issue by jtoownus** [HorizenOfficial/s-nomp#1]
A detailed specification of this task is provided at request.

**Comment by sobitha23** [comment]
good

**Comment by zxx13789999372** [comment]
好

**Comment by phamphuongss** [comment]
very gook

**Comment by phamphuongss** [comment]
very good

**Comment by Calebe44** [comment]
Bem gostei agora seria bom simplificar o maximo possivel?

**Comment by jason77794** [comment]
Nice!!! Fly to the moon!!!!

**Comment by azzamrony** [comment]
Nice projects

 znjnmxcjyeaT2bWKtRTbsNeQU135qELsjpf

**Comment by didlemiere** [comment]
good

**Comment by infernoblast** [comment]
great work

**Comment by SuryaAs** [comment]
Very good project ...
always successful...

**Comment by zxx13789999372** [comment]
K9EKgFjAUNEieFuBACBEwFtQiPRALmKCgL
---原始邮件---
发件人:&quot;Adi Saputro&quot;<notifications@github.com&gt;
发送时间:2020年7月21日 星期二 上午0:11
收件人:&quot;ZencashOfficial/s-nomp&quot;<s-nomp@noreply.github.com&gt;
抄送:&quot;zxx13789999372&quot;<313253561@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [ZencashOfficial/s-nomp] Make s-nomp sidechain compatible (#1)



Very&nbsp;good&nbsp;project&nbsp;...
always&nbsp;successful...

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by ahmedmoharm22** [comment]
مشروع جيد جدا ... ناجح دائما ...

**Comment by ahmedmoharm22** [comment]
Very good project ...
always successful...

**Comment by kimyaci8674** [comment]
very good project...

**Comment by mis121** [comment]
project yang bagus, tapi perlu perkembangan lagi kedepan

**Comment by astantoid** [comment]
Smart project, can develope everytime

**Comment by wahyucrypto1** [comment]
I do no

**Comment by wahyucrypto1** [comment]
I get 50 zen

**Comment by mis121** [comment]
i not get zen

Pada Kamis, 30 Juli 2020, wahyucrypto1 <notifications@github.com> menulis:

**Comment by imam513262** [comment]
smart project

**Comment by d032nk** [comment]
How it work

**Comment by alexfabian0** [comment]
O projeto é extremamente promissor! Estou torcendo por isso!

**Comment by trubus89** [comment]
Nice project

**Comment by svenkatagiri** [comment]
I felt very much appreciated and it really seems to be a Super Exciting Project. I am very much proud of it.

**Comment by tehiluh** [comment]
nice project

**Comment by mrhai3690** [comment]
dự án tốt! very good

**Comment by ndmsPi** [comment]
good

**Comment by mickel2006** [comment]
good

**Comment by Terry2309** [comment]
Excelente proyecto 👌

**Comment by issamtech** [comment]
I don't undertand what i do

**Comment by eduardoxmex** [comment]
I want earn 50 zen!!!!

**Comment by bangbemo** [comment]
Get 50 zen! Mantaaabb

**Comment by infernoblast** [comment]
Me too :))
    29 Ağustos 2020 Cumartesi 15:50:10 GMT+3 tarihinde, issamtech <notifications@github.com>şunu yazdı:  
 
 


I don't undertand what i do

**Comment by bangbemo** [comment]
I just remembered a zen gift

Pada tanggal Sel, 1 Sep 2020 16.36, Eren Seyrek <notifications@github.com>
menulis:

**Comment by Skaida24** [comment]
I want 50ZEN

**Comment by angievi** [comment]
Hi @Skaida24 and @infernoblast , if you are interested in working in this issue, you can let us know and we will provide you the detailed information for it. can you please give us an email so that we can provide the information? thanks!

**Comment by infernoblast** [comment]
Hi,Pls provide detailed information. Send to my this adress: erensyrk@yahoo.com.tr
Have a good day
Eren
    2 Eylül 2020 Çarşamba 06:28:29 GMT+3 tarihinde, Angievii <notifications@github.com>şunu yazdı:  
 
 


Hi @Skaida24 and @infernoblast , if you are interested in working in this issue, you can let us know and we will provide you the detailed information for it. can you please give us an email so that we can provide the information? thanks!

**Comment by angievi** [comment]
Hi @infernoblast there are no rewards if you comment on the issues. Some of the ways to earn ZEN are through:
-Our faucet: https://getzen.cash/?_lang=en 
-Our Social Media Giveaways, for example twitter : https://twitter.com/horizenglobal
-By completing HDE tasks with the proper format and requirements from the task.

Best,

Angie.

**Comment by infernoblast** [comment]
Thanks
    3 Eylül 2020 Perşembe 01:07:55 GMT+3 tarihinde, Angievii <notifications@github.com>şunu yazdı:  
 
 


Hi @infernoblast there are no rewards if you comment on the issues. Some of the ways to earn ZEN are through:
-Our faucet: https://getzen.cash/?_lang=en
-Our Social Media Giveaways, for example twitter : https://twitter.com/horizenglobal
-By completing HDE tasks with the proper format and requirements from the task.

Best,

Angie.

**Comment by cronicc** [comment]
This is a two part task

Part 1 - Analysis
- Set up a mining pool using the current https://github.com/s-nomp/s-nomp pool software and zend_oo daemons from https://github.com/HorizenOfficial/zend_oo/releases/tag/v2.1.0-beta4
- Sync stratum and payment nodes with sidechain testnet
- Configure s-nomp for zen testnet
- Try mining blocks using s-nomp

Mining blocks currently fails, there are changes in the `zen-cli getblocktemplate` format in zend_oo and new sidechain related transaction types have been added. Blocks submitted by s-nomp are rejected by zend_oo.

The analysis should focus on:
1. Why are blocks being rejected (adding debug lines to s-nomp/node-stratum-pool to dump the raw blocks that are rejected would help in debugging here)
2. What changes have to be made to https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool to make it work

Part 2 - Implementation

Create pull requests against https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool adding zend_oo sidechain testnet compatibility.

Requirements:
1. Add zen.sidechain.testnet.json example file to https://github.com/s-nomp/s-nomp/tree/master/pool_configs/examples
2. Add zen.sidechain.json to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/
3. Add support to s-nomp/node-stratum-pool for activating sidechain-testnet compatibility at a specific block (Hard Fork activation height https://github.com/HorizenOfficial/zend_oo/blob/a998fab675b05f3169b15e651b55fd39a0a02567/src/zen/forks/fork7_sidechainfork.cpp#L9). The changes needed to make s-nomp work can't have an impact on any of the other coins it supports, it must be completely backwards compatible. Activation logic should be handled by adding variables to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/zen.sidechain.json, similar to https://github.com/s-nomp/s-nomp/blob/d8d02fbebb0eb8e114a62454aae1c8b270a12d4a/coins/testnet/zen.json#L54

**Comment by angievi** [comment]
@infernoblast I've sent the instructions above to your email as well. Please let us know here if you decide to work on this task so that we can label it as a work in progress task. thank you!

**Comment by linnbenton** [comment]
how can I apply? i want learning this.

**Comment by angievi** [comment]
@linnbenton here are the steps to complete this:

This is a two part task

Part 1 - Analysis

Set up a mining pool using the current https://github.com/s-nomp/s-nomp pool software and zend_oo daemons from https://github.com/HorizenOfficial/zend_oo/releases/tag/v2.1.0-beta4
Sync stratum and payment nodes with sidechain testnet
Configure s-nomp for zen testnet
Try mining blocks using s-nomp
Mining blocks currently fails, there are changes in the zen-cli getblocktemplate format in zend_oo and new sidechain related transaction types have been added. Blocks submitted by s-nomp are rejected by zend_oo.

The analysis should focus on:

Why are blocks being rejected (adding debug lines to s-nomp/node-stratum-pool to dump the raw blocks that are rejected would help in debugging here)
What changes have to be made to https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool to make it work
Part 2 - Implementation

Create pull requests against https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool adding zend_oo sidechain testnet compatibility.

Requirements:

Add zen.sidechain.testnet.json example file to https://github.com/s-nomp/s-nomp/tree/master/pool_configs/examples
Add zen.sidechain.json to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/
Add support to s-nomp/node-stratum-pool for activating sidechain-testnet compatibility at a specific block (Hard Fork activation height https://github.com/HorizenOfficial/zend_oo/blob/a998fab675b05f3169b15e651b55fd39a0a02567/src/zen/forks/fork7_sidechainfork.cpp#L9). The changes needed to make s-nomp work can't have an impact on any of the other coins it supports, it must be completely backwards compatible. Activation logic should be handled by adding variables to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/zen.sidechain.json, similar to https://github.com/s-nomp/s-nomp/blob/d8d02fbebb0eb8e114a62454aae1c8b270a12d4a/coins/testnet/zen.json#L54

Please let us know if you would like to work on this as well as an estimated time for completion so we can mark this task as a work in progress! thank you!

**Comment by mowens785** [comment]
qa/rpc-tests/sc_02.py
Hopefully the test works

**Comment by bliinasikin-xyz** [comment]
50 zen nice😍

**Comment by radria** [comment]
Good

**Comment by CryptoMarket12** [comment]
excelente!!! informacion

**Comment by sarwono1893** [comment]
step by step horizontal travel is very detailed aiming for user convenience. Thank you for working hard so far for user convenience.😍😍😍👍👍

**Comment by mohammed1023** [comment]
Nice projects

**Comment by eaglechina** [comment]
Nice

**Comment by IHIHIKI** [comment]
50zen

**Comment by asbazar** [comment]
When we start this node how you pay zen ?

**Comment by mohammed1023** [comment]
؟؟؟؟؟؟

في السبت، ١٧ تشرين الأول، ٢٠٢٠ ١:٢٧ ص Asbazar <notifications@github.com>
كتب:

**Comment by sport83** [comment]
Part 1 - Analysis

Set up a mining pool using the current https://github.com/s-nomp/s-nomp pool software and zend_oo daemons from https://github.com/HorizenOfficial/zend_oo/releases/tag/v2.1.0-beta4
Sync stratum and payment nodes with sidechain testnet
Configure s-nomp for zen testnet
Try mining blocks using s-nomp
Mining blocks currently fails, there are changes in the zen-cli getblocktemplate format in zend_oo and new sidechain related transaction types have been added. Blocks submitted by s-nomp are rejected by zend_oo.

The analysis should focus on:

Why are blocks being rejected (adding debug lines to s-nomp/node-stratum-pool to dump the raw blocks that are rejected would help in debugging here)
What changes have to be made to https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool to make it work
Part 2 - Implementation

Create pull requests against https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool adding zend_oo sidechain testnet compatibility.

Requirements:

Add zen.sidechain.testnet.json example file to https://github.com/s-nomp/s-nomp/tree/master/pool_configs/examples
Add zen.sidechain.json to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/
Add support to s-nomp/node-stratum-pool for activating sidechain-testnet compatibility at a specific block (Hard Fork activation height https://github.com/HorizenOfficial/zend_oo/blob/a998fab675b05f3169b15e651b55fd39a0a02567/src/zen/forks/fork7_sidechainfork.cpp#L9). The changes needed to make s-nomp work can't have an impact on any of the other coins it supports, it must be completely backwards compatible. Activation logic should be handled by adding variables to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/zen.sidechain.json, similar to https://github.com/s-nomp/s-nomp/blob/d8d02fbebb0eb8e114a62454aae1c8b270a12d4a/coins/testnet/zen.json#L54

**Comment by tuttoworld** [comment]
how can I apply? i want learning this

**Comment by angievi** [comment]
Hi @tuttoworld , the steps to complete this task are:

Part 1 - Analysis

Set up a mining pool using the current https://github.com/s-nomp/s-nomp pool software and zend_oo daemons from https://github.com/HorizenOfficial/zend_oo/releases/tag/v2.1.0-beta4
Sync stratum and payment nodes with sidechain testnet
Configure s-nomp for zen testnet
Try mining blocks using s-nomp
Mining blocks currently fails, there are changes in the zen-cli getblocktemplate format in zend_oo and new sidechain related transaction types have been added. Blocks submitted by s-nomp are rejected by zend_oo.

The analysis should focus on:

Why are blocks being rejected (adding debug lines to s-nomp/node-stratum-pool to dump the raw blocks that are rejected would help in debugging here)
What changes have to be made to https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool to make it work
Part 2 - Implementation

Create pull requests against https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool adding zend_oo sidechain testnet compatibility.

Requirements:

Add zen.sidechain.testnet.json example file to https://github.com/s-nomp/s-nomp/tree/master/pool_configs/examples
Add zen.sidechain.json to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/
Add support to s-nomp/node-stratum-pool for activating sidechain-testnet compatibility at a specific block (Hard Fork activation height https://github.com/HorizenOfficial/zend_oo/blob/a998fab675b05f3169b15e651b55fd39a0a02567/src/zen/forks/fork7_sidechainfork.cpp#L9). The changes needed to make s-nomp work can't have an impact on any of the other coins it supports, it must be completely backwards compatible. Activation logic should be handled by adding variables to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/zen.sidechain.json, similar to https://github.com/s-nomp/s-nomp/blob/d8d02fbebb0eb8e114a62454aae1c8b270a12d4a/coins/testnet/zen.json#L54

Please let us know if you would like to work on this as well as an estimated time for completion so we can mark this task as a work in progress! thank you!

**Comment by jimbo313** [comment]
How do I

**Comment by jimbo313** [comment]
How do I learn about Zen to earn 50zen

**Comment by infernoblast** [comment]
why do you mean?
    7 Ocak 2021 Perşembe 08:22:26 GMT+3 tarihinde, jimbo313 <notifications@github.com>şunu yazdı:  
 
 


How do I learn about Zen to earn 50zen

**Comment by tonytran1307** [comment]
Hi Horizen community ! I have chat with admin on Telegram group. I want to contribute about this bounty, So should I start with  whose admin ? Please clarify for me ! Thank you and good luck for everyone !

**Comment by bswidzinski** [comment]
Is it still available?
https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/zen.sidechain.json returns 404

**Comment by luisantoniocrag** [comment]
is this available? I'm deploying everything so that I can test and study the structure to form a block on the sidechain.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 

Yes, this is still available but if you are starting to work on it, please claim the task here. We then expect regular updates to keep the task with you. If we do not hear anything for over 2 weeks, another community member will be able to claim it.

**Comment by luisantoniocrag** [comment]
Sure @PowerVANO 

I'm working on it! =)

**Comment by mohammed1023** [comment]
How he benefited from the bonus

في الجمعة، ١٢ آذار، ٢٠٢١ ١١:٥٧ م luisantoniocrag ***@***.***>
كتب:

**Comment by PowerVANO** [comment]
@luisantoniocrag Great!

We expect an update from you in a week then to follow the 2-week cadence.

**Comment by mohamadfadil** [comment]
This is a two part task

Part 1 - Analysis

Set up a mining pool using the current https://github.com/s-nomp/s-nomp pool software and zend_oo daemons from https://github.com/HorizenOfficial/zend_oo/releases/tag/v2.1.0-beta4
Sync stratum and payment nodes with sidechain testnet
Configure s-nomp for zen testnet
Try mining blocks using s-nomp
Mining blocks currently fails, there are changes in the zen-cli getblocktemplate format in zend_oo and new sidechain related transaction types have been added. Blocks submitted by s-nomp are rejected by zend_oo.

The analysis should focus on: 1. Why are blocks being rejected (adding debug lines to s-nomp/node-stratum-pool to dump the raw blocks that are rejected would help in debugging here) 2. What changes have to be made to https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool to make it work

Part 2 - Implementation

Create pull requests against https://github.com/s-nomp/s-nomp and/or https://github.com/s-nomp/node-stratum-pool adding zend_oo sidechain testnet compatibility.

Requirements: 1. Add zen.sidechain.testnet.json example file to https://github.com/s-nomp/s-nomp/tree/master/pool_configs/examples 2. Add zen.sidechain.json to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/ 3. Add support to s-nomp/node-stratum-pool for activating sidechain-testnet compatibility at a specific block (Hard Fork activation height https://github.com/HorizenOfficial/zend_oo/blob/a998fab675b05f3169b15e651b55fd39a0a02567/src/zen/forks/fork7_sidechainfork.cpp#L9). The changes needed to make s-nomp work can't have an impact on any of the other coins it supports, it must be completely backwards compatible. Activation logic should be handled by adding variables to https://github.com/s-nomp/s-nomp/blob/master/coins/testnet/zen.sidechain.json, similar to https://github.com/s-nomp/s-nomp/blob/d8d02fbebb0eb8e114a62454aae1c8b270a12d4a/coins/testnet/zen.json#L54

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO sorry ...

![IMG_20210326_012338514](https://user-images.githubusercontent.com/42625753/112597646-01a2e280-8dd3-11eb-89d9-700d44e09069.jpg)

I just managed to setup all to see the problem. I will take all day to discover the error, as mentioned there are changes in the `zen-cli getblocktemplate `...

**Comment by PowerVANO** [comment]
Thanks @luisantoniocrag! 

Please update us with your findings next week.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 
Do you have any updates?

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 

We will be having a new release of Zendoo soon with lots of changes which turns out will invalidate your current work.

With that in mind, we decided to deprecate this task.

Please stop working on it and I am sorry that you have already spent some time on it.

This one can be closed @cronicc @angievi

**Comment by luisantoniocrag** [comment]
@PowerVANO  Don't worry!

I learned a lot trying to solve this issue! the problem was that has a new paramater to getblocktemplate: `certificates[]`

I will be aware of these changes and will try to solve the next issues in the HDE when they are published =)

**Comment by PowerVANO** [comment]
Great to hear that @luisantoniocrag!

**Comment by jmarcosoliver** [comment]
hello... send me details to my email: jmarcosoliver@gmail.com

**Comment by mohammed1023** [comment]
I did not understand you any details

في الأحد، ١٨ نيسان، ٢٠٢١ ٥:٣٢ ص jmarcosoliver ***@***.***>
كتب:
